# 4.1 Data Manipulation
### 2018320178 Kim Youngchan

In [8]:
import torch
torch.rand(10)

tensor([0.0342, 0.3578, 0.6087, 0.1115, 0.5124, 0.5359, 0.8757, 0.4210, 0.2114,
        0.1773])

pytorch를 import하고 torch.rand()를 통해 테스트를 해보았다.

In [28]:
x = torch.arange(16, dtype=torch.float64)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.], dtype=torch.float64)


In [17]:
x.shape

torch.Size([16])

자료형 옆의 숫자는 bit 수를 나타내고, integer, complex, boolean 등의 attribute가 있다.

In [32]:
x = x.reshape((4, 4))
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]], dtype=torch.float64)

In [34]:
x = x.reshape(2, 8)
x

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]], dtype=torch.float64)

In [35]:
x = x.reshape(((8, 2)))
x

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]], dtype=torch.float64)

In [37]:
x = x.reshape((2, -1))
x

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]], dtype=torch.float64)

reshape() 여러가지 방법으로 사용해보기

In [39]:
torch.FloatTensor(2, 3)

tensor([[1.7664e-04, 3.4031e-06, 2.1590e-04],
        [3.3209e-09, 1.0559e-08, 1.7473e-04]])

In [40]:
torch.Tensor(2, 3)

tensor([[0.0000e+00, 1.3593e-43, 1.8754e+28],
        [3.2175e+21, 2.7446e-06, 1.3029e-11]])

In [44]:
torch.empty(2, 3)

tensor([[1.6502e-07, 1.0314e-08, 6.6291e-10],
        [2.7179e-06, 4.2251e-05, 5.4452e-05]])

torch.FloatTensor()와 torch.empty()는 같은 작업을 수행한다.

In [45]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

모든 원소가 0인 3 by 4 행렬을 2개 만듦  
*ones()는 모든 원소를 1인 행렬을 만듦

In [50]:
y = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(y)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


행렬의 원소를 명시해줄 수도 있음

In [51]:
torch.randn(4, 2)

tensor([[-2.0177,  1.2143],
        [ 0.4518, -0.0028],
        [-0.2110, -0.7507],
        [ 0.1510,  0.4596]])

난수도 생성할 수 있다.  
각 원소가 unit normal distribution에 의해 샘플링되는 것으로 보인다

## Operations
### element-wise operations

In [56]:
x = torch.tensor([1, 2, 4, 8], dtype=torch.float32)
y = torch.ones_like(x) * 2
print('x =', x)
print('y =', y)
print('x + y =', x + y)
print('x - y =', x - y)
print('x * y =', x * y)
print('x / y =', x / y)
torch.exp(x)

x = tensor([1., 2., 4., 8.])
y = tensor([2., 2., 2., 2.])
x + y = tensor([ 3.,  4.,  6., 10.])
x - y = tensor([-1.,  0.,  2.,  6.])
x * y = tensor([ 2.,  4.,  8., 16.])
x / y = tensor([0.5000, 1.0000, 2.0000, 4.0000])


tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

'+' : element-wise addition  
'-' : element-wise subtraction  
'*' : element-wise multiplication  
'/' : element-wise division

### matrix operations

In [58]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=torch.float32)
print(x.dtype)
print('x =', x)
print('y =', y)
torch.mm(x, y.t())

torch.float32
x = tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
y = tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


tensor([[ 20.,  44.,  68.],
        [ 60., 148., 236.],
        [100., 252., 404.]])

`mm` or `matmul` : 행렬 곱(matrix multiplication)  
`.t()` : 전치 행렬(transpose)

In [59]:
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [60]:
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  5.,  6.,  7.,  8.],
        [ 8.,  9., 10., 11.,  9., 10., 11., 12.]])

In [62]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [63]:
x.sum()

tensor(66.)

## Broadcast Mechanism  
tensor의 shape가 다를 때

In [64]:
a = torch.arange(3, dtype=torch.float32).reshape((3, 1))
b = torch.arange(2, dtype=torch.float32).reshape((1, 2))
a, b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

In [65]:
a + b

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

결과 형태를 잘 봅시다

## Indexing and Slicing
Python array와 같이 tensor의 element도 index로 접근 가능하다.  
첫 원소는 0의 index를 갖는다.  
range는 첫 번째 원소는 포함하고, 마지막 원소는 포함하지 않는다.  
예를 들어 `1:3`은 index 1, 2를 뜻한다.

In [74]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [83]:
temp = x.reshape((6, 2))
print(temp)
temp[0:3]

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])


tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [87]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Saving Memory

In [89]:
before = id(y)
y = y + x
id(y) == before

False

In [90]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2397986303168
id(z): 2397986303168


In [92]:
before = id(z)
torch.add(x, y, out=z)
id(z) == before

True

In [93]:
before = id(x)
x += y
id(x) == before

True

## Mutual Transformation of PyTorch and NumPy
PyTorch Tensor와 NumPy Array 사이의 전환

In [94]:
a = x.numpy()
print(type(a))
b = torch.tensor(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [95]:
a = torch.tensor(a)
b = b.numpy()
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
